AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi
Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDER_TABLE: !Ref OrderTable

Resources:
  OrderTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.pramod.aws.api.CreateOrderLamda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrderTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.pramod.aws.api.ReadOrderLamda::readOrder
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrderTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET